### ISSUE TITLE
Pathy.is_dir() return True on buckets that don't exist

### ISSUE THREAD

**Issue by yaelmi3** [justindujardin/gcspath#107]
env: python3.10; tested with GS

```
Pathy("gs://i-am-not-here").is_dir()
Out: True
```

This occurs, because [the check](https://github.com/justindujardin/pathy/blob/master/pathy/__init__.py#L625) in `is_dir` return True, in case the provided input is a bucket, without a key, but doesn't really check if this bucket exists

possible solution: https://github.com/justindujardin/pathy/pull/108

**Comment by justindujardin** [comment]
Thanks for the fix to go along with your bug report. 💯🙇
