### ISSUE TITLE
S3 Glob hangs

### ISSUE THREAD

**Issue by zbyte64** [justindujardin/gcspath#67]
When I run `list(path.glob("*/metadata.json"))` the code will hang on an S3 path but not on a local path. But if the second portion include a "*" then it will work, ie: `list(path.glob("*/*.json"))`

**Comment by justindujardin** [comment]
@zbyte64 thanks for the report. I added a test case that tries to reproduce your issue, but it passes with s3 no problem: https://github.com/justindujardin/pathy/pull/92

Can you tell me more about your bucket setup? Are there hundreds or thousands of folders you're trying to match with that wildcard maybe?

**Comment by justindujardin** [comment]
Going to close this as stale. Feel free to reopen with a full reproduction case
