### ISSUE TITLE
A path containing double slashes for some protocol (e.g. sftp)

### ISSUE THREAD

**Issue by wookayin** [justindujardin/gcspath#91]
```
In [1]: s = pathy.Pathy("sftp://foobar//etc/passwd")

In [2]: s
Out[2]: Pathy('sftp://foobar/etc/passwd')
```

It looks like Pathy always perform path normalization, including double slashes in the path `//` normalized to `/`; but in some protocols (e.g., sftp) double slashes are [often][1] [used][2] to represent the absolute path aside from the CWD. I don't think this is a standard, but the URI ([RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986)) at least allows multiple forward slashes *as a valid URI* although its semantic meaning may vary by server implementations. See [this article][SO] for more details.

[SO]: https://stackoverflow.com/questions/20523318/is-a-url-with-in-the-path-section-valid

[1]: https://quickview.cloudapps.cisco.com/quickview/bug/CSCvv93442
[2]: https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#sftp

I know `sftp` is NOT a supported protocol by pathy but I was considering this as a `PurePath` alternative to `pathlib.Path` (which however normalizes the protocol `gs://` -> `gs:/`). That said, in S3 or GCS, `//` seems to have no meaning.

Is there any way to make the remote path aware of multiple slashes, upon some configurations?

**Comment by justindujardin** [comment]
@wookayin thanks for asking. I didn't know that SFTP used double slashes in paths.

It's totally possible that Pathy could be aware of double slashes, but it'd probably have to be part of a client adapter for the specific scheme that uses them.

While there's not a spot for path formatting in the clients right now (it takes place [here ](https://github.com/justindujardin/pathy/blob/490ecb836071b78676e3acacb42725b86ef10e73/pathy/__init__.py#L316) and [here](https://github.com/justindujardin/pathy/blob/490ecb836071b78676e3acacb42725b86ef10e73/pathy/__init__.py#L239)) it could be added for a new adapter that needs it. The basic idea would be to expose the client adapter to the parse/format parts functions. Then each adapter could format the paths as needed.

**Comment by justindujardin** [comment]
I'm going to close this as not planned. Feel free to reopen if you think this is a mistake
